version: "3.7"

services:
  bwt-test-task:
    image: bwt-test-task
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - /tmp:/tmp
    - /etc:/etchost:ro
    ports:
    - target: 8080
      published: 8080
      protocol: tcp
      mode: host
    - target: 8081
      published: 8081
      protocol: tcp
      mode: host
    networks:
    - webnet
    environment:
    - "SPRING_PROFILES_ACTIVE=[PROFILE]"
    - "JAVA_OPTS=[JAVA_OPTS]"

networks:
    webnet:
      driver: bridge